
---
- name: Install and Start httpd service
  hosts: all
  remote_user: root

  tasks:
    - name: Install httpd
      apt:
        name: httpd
        state: present
    - name: Start httpd
      service: 
        name: httpd
        state: present
